# Generated by Django 5.0.6 on 2024-05-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_questions_answer_questions_ans1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='correct_ans',
            field=models.CharField(choices=[], max_length=100, null=True),
        ),
    ]
