# Generated by Django 5.0.6 on 2024-05-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_questions_correct_ans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='correct_ans',
            field=models.CharField(choices=[(models.CharField(max_length=100, null=True), models.CharField(max_length=100, null=True)), (models.CharField(max_length=100, null=True), models.CharField(max_length=100, null=True)), (models.CharField(max_length=100, null=True), models.CharField(max_length=100, null=True)), (models.CharField(max_length=100, null=True), models.CharField(max_length=100, null=True))], max_length=100, null=True),
        ),
    ]
