# Generated by Django 5.0.6 on 2024-05-22 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_category_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_q', to='accounts.category_questions'),
        ),
    ]
