# Generated by Django 5.0.6 on 2024-05-23 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_questions_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat_ques', to='accounts.category_questions'),
        ),
    ]
