# Generated by Django 5.0.6 on 2024-06-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='solution',
            field=models.FileField(null=True, upload_to='solution'),
        ),
    ]
