# Generated by Django 5.0.6 on 2024-06-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_questions_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='solution',
            field=models.FileField(blank=True, null=True, upload_to='solution'),
        ),
    ]
