# Generated by Django 5.0.6 on 2024-06-06 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_students_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='students',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_stu', to='accounts.trainers'),
        ),
    ]
