# Generated by Django 5.0.6 on 2024-06-06 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_trainers_alter_students_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainers',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_cou', to='accounts.courses'),
        ),
    ]
