# Generated by Django 5.0.6 on 2024-06-07 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_students_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.ManyToManyField(related_name='cat_exam', to='accounts.category_questions')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_exam', to='accounts.students')),
            ],
        ),
    ]
