# Generated by Django 5.0.6 on 2024-06-08 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_examassign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examassign',
            name='student',
        ),
    ]
