# Generated by Django 5.0.6 on 2024-06-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_examassign_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='student_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
