# Generated by Django 5.0.6 on 2024-06-11 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_machinetest_machinetestanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='img',
        ),
        migrations.CreateModel(
            name='AttendedStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='att_b', to='accounts.batchs')),
                ('cat', models.ManyToManyField(to='accounts.category_questions')),
            ],
        ),
    ]
