# Generated by Django 5.0.6 on 2024-06-12 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_remove_questions_img_attendedstudents'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendedstudents',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='att_cou', to='accounts.courses'),
        ),
        migrations.CreateModel(
            name='SetOfExams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examname', models.CharField(max_length=100)),
                ('cat', models.ManyToManyField(to='accounts.category_questions')),
            ],
        ),
    ]
