# Generated by Django 5.0.6 on 2024-06-12 10:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_attendedstudents_course_setofexams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendedstudents',
            name='cat',
        ),
        migrations.AddField(
            model_name='attendedstudents',
            name='set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='att_set', to='accounts.setofexams'),
        ),
        migrations.AddField(
            model_name='setofexams',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=7200)),
        ),
        migrations.AddField(
            model_name='setofexams',
            name='exam_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
