# Generated by Django 5.0.6 on 2024-06-12 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_remove_attendedstudents_cat_attendedstudents_set_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setofexams',
            name='cat',
        ),
        migrations.DeleteModel(
            name='AttendedStudents',
        ),
        migrations.DeleteModel(
            name='SetOfExams',
        ),
    ]
