# Generated by Django 5.0.6 on 2024-06-12 10:28

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_remove_setofexams_cat_delete_attendedstudents_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetOfExams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examname', models.CharField(max_length=100)),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=7200))),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('exam_link', models.URLField(blank=True, null=True)),
                ('cat', models.ManyToManyField(to='accounts.category_questions')),
            ],
        ),
        migrations.CreateModel(
            name='AttendedStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='att_b', to='accounts.batchs')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='att_cou', to='accounts.courses')),
                ('set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='att_set', to='accounts.setofexams')),
            ],
        ),
    ]
