# Generated by Django 5.0.6 on 2024-06-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_setofexams_attendedstudents'),
    ]

    operations = [
        migrations.AddField(
            model_name='setofexams',
            name='attendedstudentscount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
