# Generated by Django 5.0.6 on 2024-06-13 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_setofexams_attendedstudentscount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setofexams',
            name='attendedstudentscount',
        ),
    ]
