# Generated by Django 5.0.6 on 2024-06-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_alter_answers_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendedstudents',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
